// Mocks generated by Mockito 5.4.6 from annotations
// in memories_project/test/services/contact_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i3;
import 'package:memories_project/features/album/models/album.dart' as _i7;
import 'package:memories_project/features/user/models/app_user.dart' as _i5;
import 'package:memories_project/features/user/services/contact_service.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseFirestore_0 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseAuth_1 extends _i1.SmartFake implements _i3.FirebaseAuth {
  _FakeFirebaseAuth_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ContactService].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactService extends _i1.Mock implements _i4.ContactService {
  MockContactService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseFirestore get firestore =>
      (super.noSuchMethod(
            Invocation.getter(#firestore),
            returnValue: _FakeFirebaseFirestore_0(
              this,
              Invocation.getter(#firestore),
            ),
          )
          as _i2.FirebaseFirestore);

  @override
  _i3.FirebaseAuth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeFirebaseAuth_1(this, Invocation.getter(#auth)),
          )
          as _i3.FirebaseAuth);

  @override
  List<_i5.AppUser> get friends =>
      (super.noSuchMethod(
            Invocation.getter(#friends),
            returnValue: <_i5.AppUser>[],
          )
          as List<_i5.AppUser>);

  @override
  int get invitationsSent =>
      (super.noSuchMethod(Invocation.getter(#invitationsSent), returnValue: 0)
          as int);

  @override
  int get totalInvitationsSent =>
      (super.noSuchMethod(
            Invocation.getter(#totalInvitationsSent),
            returnValue: 0,
          )
          as int);

  @override
  set friends(List<_i5.AppUser>? _friends) => super.noSuchMethod(
    Invocation.setter(#friends, _friends),
    returnValueForMissingStub: null,
  );

  @override
  set invitationsSent(int? _invitationsSent) => super.noSuchMethod(
    Invocation.setter(#invitationsSent, _invitationsSent),
    returnValueForMissingStub: null,
  );

  @override
  set totalInvitationsSent(int? _totalInvitationsSent) => super.noSuchMethod(
    Invocation.setter(#totalInvitationsSent, _totalInvitationsSent),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i5.AppUser?> loadCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#loadCurrentUser, []),
            returnValue: _i6.Future<_i5.AppUser?>.value(),
          )
          as _i6.Future<_i5.AppUser?>);

  @override
  _i6.Future<Map<String, dynamic>> loadFriendsData() =>
      (super.noSuchMethod(
            Invocation.method(#loadFriendsData, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> sendInvite() =>
      (super.noSuchMethod(
            Invocation.method(#sendInvite, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> getInvitationsSent() =>
      (super.noSuchMethod(
            Invocation.method(#getInvitationsSent, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> loadFriends() =>
      (super.noSuchMethod(
            Invocation.method(#loadFriends, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeFriend(_i5.AppUser? friend) =>
      (super.noSuchMethod(
            Invocation.method(#removeFriend, [friend]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> addFriend(String? friendId, String? inviterUserId) =>
      (super.noSuchMethod(
            Invocation.method(#addFriend, [friendId, inviterUserId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> shareAlbumWithUser(_i7.Album? album, String? friendUid) =>
      (super.noSuchMethod(
            Invocation.method(#shareAlbumWithUser, [album, friendUid]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
