// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWodRvQ9ROjzjBQhD01kgs7XyuXw47x0E',
    appId: '1:226377233333:web:f5ff05fa80287971cc9ffc',
    messagingSenderId: '226377233333',
    projectId: 'memories-7bdc6',
    authDomain: 'memories-7bdc6.firebaseapp.com',
    storageBucket: 'memories-7bdc6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfv6pYVxcDhfnq0rj2MzcIXTwvxxUgJxY',
    appId: '1:226377233333:android:e2e58902906ecb63cc9ffc',
    messagingSenderId: '226377233333',
    projectId: 'memories-7bdc6',
    storageBucket: 'memories-7bdc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqeUhjGMvQByzXsfWbjOkzRa0pz5EyGkg',
    appId: '1:226377233333:ios:948614c366f95681cc9ffc',
    messagingSenderId: '226377233333',
    projectId: 'memories-7bdc6',
    storageBucket: 'memories-7bdc6.firebasestorage.app',
    iosBundleId: 'com.example.memoriesProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqeUhjGMvQByzXsfWbjOkzRa0pz5EyGkg',
    appId: '1:226377233333:ios:948614c366f95681cc9ffc',
    messagingSenderId: '226377233333',
    projectId: 'memories-7bdc6',
    storageBucket: 'memories-7bdc6.firebasestorage.app',
    iosBundleId: 'com.example.memoriesProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWodRvQ9ROjzjBQhD01kgs7XyuXw47x0E',
    appId: '1:226377233333:web:7eb8fd20c7f807eecc9ffc',
    messagingSenderId: '226377233333',
    projectId: 'memories-7bdc6',
    authDomain: 'memories-7bdc6.firebaseapp.com',
    storageBucket: 'memories-7bdc6.firebasestorage.app',
  );
}
