name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull and Use Docker Hub Image
        run: |
          docker pull lmagniez03/flutter-firebase:latest

      - name: Configure Safe Directory
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            lmagniez03/flutter-firebase:latest \
            git config --global --add safe.directory /opt/flutter

      - name: Check Flutter Version
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            lmagniez03/flutter-firebase:latest \
            bash -c "flutter --version"

      - name: Debug Environment
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            lmagniez03/flutter-firebase:latest \
            bash -c "env"

      - name: Run Commands Manually
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }} \
            lmagniez03/flutter-firebase:latest \
            bash -c "flutter pub get && flutter build web --release && firebase deploy --only hosting --project memories-7bdc6"

      - name: Deploy to Firebase Hosting
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }} \
            lmagniez03/flutter-firebase:latest \
            bash -c "flutter pub get && flutter build web --release && firebase deploy --only hosting --project memories-7bdc6"

      - name: Set up Environment Variables (optionnel)
        run: |
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV
          echo "NINJA_API_KEY=${{ secrets.NINJA_API_KEY }}" >> $GITHUB_ENV
