name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Flutter Docker Image
        run: |
          docker pull ghcr.io/cirruslabs/flutter:3.32.0-0.5.pre
          docker run --rm -v ${{ github.workspace }}:/app -w /app ghcr.io/cirruslabs/flutter:3.32.0-0.5.pre flutter clean

      - name: Get Pub Dependencies
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app ghcr.io/cirruslabs/flutter:3.32.0-0.5.pre flutter pub get

      - name: Build Flutter Web
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app ghcr.io/cirruslabs/flutter:3.32.0-0.5.pre flutter build web --release --verbose

      - name: Use Firebase CLI Docker Image
        run: |
          docker pull firebase/cli
          docker run --rm -v ${{ github.workspace }}:/app -w /app -e FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }} firebase/cli firebase deploy --only hosting --project memories-7bdc6

      - name: Set up Environment Variables
        run: |
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV
          echo "NINJA_API_KEY=${{ secrets.NINJA_API_KEY }}" >> $GITHUB_ENV
