name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Replace with your default branch
  pull_request:
    branches:
      - main # Replace with your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v3
        with:
          flutter-version: '3.24.1'  # Specify the Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ensure compatibility with Firebase CLI

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project <firebase-project-id>
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Set up Environment Variables
        run: echo "VARIABLE_NAME=value" >> $GITHUB_ENV
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          NINJA_API_KEY: ${{ secrets.NINJA_API_KEY }}

