name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
            docker build -t flutter-firebase-image . 

      - name: Build and Deploy to Firebase Hosting
        uses: docker://flutter-firebase-image
        with:
          args: |
            flutter pub get
            flutter build web --release
            firebase deploy --only hosting --project memories-7bdc6
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


      - name: Set up Environment Variables
        run: echo "VARIABLE_NAME=value" >> $GITHUB_ENV
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          NINJA_API_KEY: ${{ secrets.NINJA_API_KEY }}

