name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.19.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.1.0'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Environment Variables
        run: |
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV
          echo "NINJA_API_KEY=${{ secrets.NINJA_API_KEY }}" >> $GITHUB_ENV

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project memories-7bdc6
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


