name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull and Use Docker Hub Image
        run: |
          docker pull lmagniez03/flutter-custom:latest

      - name: Configure Safe Directory
        run: |
          docker run --rm --user root \
            -v ${{ github.workspace }}:/app \
            -w /app \
           lmagniez03/flutter-custom:latest \
            git config --global --add safe.directory /opt/flutter

      - name: Change Permissions for Flutter Directory
        run: |
          docker run --rm --user root \
            -v ${{ github.workspace }}:/app \
            -w /app \
            lmagniez03/flutter-custom:latest \
            bash -c "chown -R 1001:1001 /opt/flutter"

      - name: Clean Flutter Cache
        run: |
          docker run --rm --user root \
            -v ${{ github.workspace }}:/app \
            -w /app \
            lmagniez03/flutter-custom:latest \
            bash -c "flutter clean"

      - name: Verify Flutter Directory Permissions
        run: |
          docker run --rm --user root \
            -v ${{ github.workspace }}:/app \
            -w /app \
            lmagniez03/flutter-custom:latest \
            bash -c "ls -l /opt/flutter"

      - name: Check Flutter and Dart Versions
        run: |
          docker run --rm --user root \
            -v ${{ github.workspace }}:/app \
            -w /app \
            lmagniez03/flutter-custom:latest \
            bash -c "flutter --version && dart --version"

      - name: Remove sky_engine Dependency
        run: |
          docker run --rm --user root \
            -v ${{ github.workspace }}:/app \
            -w /app \
            lmagniez03/flutter-custom:latest \
            bash -c "sed -i '/sky_engine/d' pubspec.yaml"

      - name: Debug Pub Dependencies
        run: |
          docker run --rm --user root \
            -v ${{ github.workspace }}:/app \
            -w /app \
            lmagniez03/flutter-custom:latest \
            bash -c "flutter pub outdated"

      - name: Get Pub Dependencies
        run: |
          docker run --rm --user root \
            -v ${{ github.workspace }}:/app \
            -w /app \
            lmagniez03/flutter-custom:latest \
            bash -c "flutter pub get"

      - name: Debug Environment
        run: |
          docker run --rm --user root \
            -v ${{ github.workspace }}:/app \
            -w /app \
            lmagniez03/flutter-custom:latest \
            bash -c "env"

      - name: Build Flutter Web
        run: |
          docker run --rm --user root \
            -v ${{ github.workspace }}:/app \
            -w /app \
            lmagniez03/flutter-custom:latest \
            bash -c "flutter build web --release --verbose"

      - name: Deploy to Firebase Hosting
        run: |
          docker run --rm --user root \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }} \
            lmagniez03/flutter-custom:latest \
            bash -c "flutter pub get && flutter build web --release && firebase deploy --only hosting --project memories-7bdc6"

      - name: Check Firebase Deployment Logs
        run: |
          docker run --rm --user root \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }} \
            lmagniez03/flutter-custom:latest \
            bash -c "firebase deploy --only hosting --project memories-7bdc6 --debug"

      - name: Set up Environment Variables
        run: |
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV
          echo "NINJA_API_KEY=${{ secrets.NINJA_API_KEY }}" >> $GITHUB_ENV
